### ISSUE TITLE
Updating plugin in docker WP erases folder and fails

### ISSUE THREAD

**Issue by braco** [crossfield/gutenblock#16]
Steps:

1. Run docker
2. Go into WP plugins – "an update is available" – update this plugin

The content of the blocks folder is deleted, and even when creating a new folder, WP is ignoring the plugin.

This is shown in console:

```
ERROR in ./index.js
Module build failed (from ./loader.js):
Error: ENOENT: no such file or directory, open '/private/var/www/temp/blocks/index.js'
 @ multi ././index.js main[0]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by zackify** [comment]
This is because that plugin name is taken by someone else. Really when you release it, it needs a different prefix. It just hasn’t been a priority for me but it is in another ticket and I’ll try to work on this plugin next weekend and clear out these issues. https://github.com/crossfield/gutenblock/issues/8
